apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bsms-backend-hpa
  namespace: pitin-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bsms-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
